force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C - {0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Authors_name__c.field-meta.xml
<CustomField>
    <fullName>Authors_name__c</fullName>
    <label>Authors name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment__c/fields/CommentId__c.field-meta.xml
<CustomField>
    <fullName>CommentId__c</fullName>
    <externalId>true</externalId>
    <label>CommentId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Post_Id__c.field-meta.xml
<CustomField>
    <fullName>Post_Id__c</fullName>
    <label>Post Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CommentsLocatorQueueable.cls
public with sharing class CommentsLocatorQueueable implements Queueable, Database.AllowsCallouts{
 
    private static String ENDPOINT_BASE = 'callout:JSONplaceholder';

    private class Comment{
        String body;
        String email;
        Integer id; 
        String name; 
        Integer postId;
    }

    public void execute(QueueableContext context){

        List<Comment__c> commentsToUpsert = new List<Comment__c>();
        List<Comment> returnedCommentsList = getAllCommentsCallout();
        if(returnedCommentsList!=null){

            for(Comment comment_i : returnedCommentsList){
               commentsToUpsert.add(new Comment__c(Body__c = comment_i.body,
                                                    Email__c = comment_i.email,
                                                    CommentId__c = comment_i.id,
                                                    Authors_name__c = comment_i.name,
                                                    Post_Id__c = comment_i.postId));
            }

            upsert commentsToUpsert CommentId__c;
        }

    }

    private static List<Comment> getAllCommentsCallout(){

        String endpoint = ENDPOINT_BASE + '/comments';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        if(response.getStatusCode() == 200){

            List<Comment> postsList = (List<Comment>) JSON.deserialize(response.getBody(), List<Comment>.class);
            return postsList;
        }
        return null;
    }

}