force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C - {0000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Post__c.field-meta.xml
<CustomField>
    <fullName>Post__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post</label>
    <referenceTo>Post__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Post__c/Post__c.object-meta.xml
<CustomObject>
    <label>Post</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Post Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CommentsLocatorQueueableTest.cls
@isTest
public class CommentsLocatorQueueableTest {
    
    @TestSetup
    static void setup(){
        Post__c post = PostsTestDataFactory.getPost(1);
        insert post;
    }

    @isTest
    private static void getCommentsTest(){
        
        CommentsCalloutMock commentsCalloutMock = new CommentsCalloutMock();
        Test.setMock(HttpCalloutMock.class,commentsCalloutMock);

        Test.startTest();
            System.enqueueJob(new CommentsLocatorQueueable());
        Test.stopTest();

        List<Comment__c> comments = [SELECT Id
                                    FROM Comment__c];  

        System.assertEquals(1,comments.size(),'Comments weren`t returned');
    }
}