force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S - {0000}</displayFormat>
        <label>Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateStudentsAmountScheduledBatchTest.cls
@isTest
public class UpdateStudentsAmountScheduledBatchTest {
    
    @TestSetup
    public static void setup(){
        List<Department__c> departments = TestDataFactory.getDepartmetList(2);
        List<Group__c> groups = new List<Group__c>();
        List<Student__c> students = new List<Student__c>();
        insert departments;

        for(Department__c dep_i : departments){
            groups.addAll(TestDataFactory.getGroupsForDepartment(dep_i.Id, 2));
        }
        insert groups;

        for(Group__c group_i : groups){
            students.addAll(TestDataFactory.getStudentsForGroup(group_i.Id, 30));
        }
        insert students;
    }

    @isTest
    private static void TotalStudentsBatchTest(){

        Test.startTest();
        Id batchId = Database.executeBatch(new UpdateStudentsAmountScheduledBatch());
        Test.stopTest();

        List<Department__c> departments = [SELECT Id, Total_Students__c
                                            FROM Department__c];
        System.assertEquals(30, departments[0].Total_Students__c, 'Wrong total students calculation for 1 department');
        System.assertEquals(30, departments[1].Total_Students__c, 'Wrong total students calculation for 2 department');
    }

    @isTest
    private static void SchedulerTest(){
        String CRON_EXP = '0 0 6 * * ? *';
        Date tomorrowDate = Date.today().addDays(1);
        Datetime expectedDatetime = Datetime.newInstance(tomorrowDate.year(), tomorrowDate.month(), tomorrowDate.day(), 6, 0, 0);
        Test.startTest();
        String jobId = System.schedule('Recalculate total students count', CRON_EXP, new UpdateStudentsAmountScheduledBatch());
        Test.stopTest();
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(expectedDatetime, ct.NextFireTime, 'Scheduler wasn`t started');   
    }

}