force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group__c/fields/Curator__c.field-meta.xml
<CustomField>
    <fullName>Curator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curator</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Group__c/fields/Education_Form__c.field-meta.xml
<CustomField>
    <fullName>Education_Form__c</fullName>
    <label>Education Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>full-time</fullName>
            </value>
            <value>
                <fullName>distance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group__c/fields/Education_year__c.field-meta.xml
<CustomField>
    <fullName>Education_year__c</fullName>
    <label>Education Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Group__c/fields/Students_Amount__c.field-meta.xml
<CustomField>
    <fullName>Students_Amount__c</fullName>
    <label>Students Amount</label>
    <summaryForeignKey>Student__c.Group__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <displayFormat>T - {0000}</displayFormat>
        <label>Teacher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Teachers</relationshipLabel>
    <relationshipName>Teachers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Teacher_Name__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Name__c</fullName>
    <label>Teacher Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/showGroupsTableController.cls
public with sharing class showGroupsTableController {
    
    @AuraEnabled(cacheable=true)
    public static Response getGroups(Id departmentId){
        Response resp;
        try {
            List<Group__c> groupsList = [SELECT Id, Name, Students_Amount__c, Education_year__c, Education_Form__c, Curator__r.Teacher_Name__c
                                        FROM Group__c
                                        WHERE Department__c = :departmentId];

            resp = new Response(groupsList);
        } catch (Exception e) {
            resp = new Response(e);
        }
        return resp;
    }
}